### ISSUE TITLE
justification for polynomial power in adjusted route efficiency calculation (and other coefficients)

### ISSUE THREAD

**Issue by Davidrxyang** [Davidrxyang/raines-2024-line-addition-problem#106]
how do we justify the value of the polynomial power in our adjusted route efficiency calculation, and other coefficient parameters? 

- the key contribution of this project is not necessarily creating a tool to immediately generate practical public transit routes, but instead provide a platform to test the effects on generated lines from changing different parameters involved in the evaluation calculation system. 

- it is sufficient to give the user/reader liberty to configure the parameters for evaluation functions however they like

- here is what we do have to include: 
1. justification for the functional form of the math: the polynomial degree is an "arbitrary" parameter, but why did we choose a polynomial functional form to model route efficiency? (to penalize low efficiency routes more)
2. recommendations for parameters - we should provide a set of recommended parameters for the user/reader to start with
- for these recommendations, I believe it is sufficient to simply say we arrived at these parameters through testing our algorithm and comparing results intuitively with typical transit line desing. We may also want to add graphics plotting the behavior of evaluation methods with different parameters and how they affect each other - since most calculations are used by other calculations.

**Comment by henrydeng2002** [comment]
one thing to consider in justification is the induced demand effect - high complexity routes are inherently going to have less people traveling through it currently, as there are more efficient ways to travel between the points, but when a more efficient connection is added, more demand will be created between the stations. the polynomial degree somewhat represents this induced demand (find paper to support this claim)

this is also an important distinction to make somewhere in the notes & analysis of the paper - and o-d demand matrix is different from an o-d trips matrix, since some people might want to travel from one place to another (included in the demand matrix) but won't actually travel because of inefficient routing (not included in the trips matrix). we are using trips data, so important to include this distinction
